=== hunter-asd/XSW/acq/templates/acq/ACQ.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- EXL Data Acquisiton Configuration Information -->
<!--  designed by Dr Song xianming from SWIP DAS in 2019.4.4-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ACQ">
		<xs:annotation>
			<xs:documentation>Units in this file: current=kA, voltage=V, length=mm, time=ms, frequency=Hz</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Header">
					<xs:annotation>
						<xs:documentation>header information</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="version" type="xs:decimal" default="1.0"/>
							<xs:element name="operator" type="xs:string" default="songxm"/>
							<xs:element name="shotnum" type="xs:string" default="20000"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Channel" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>The root element is usually named the same as the doctype.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<!--  unsignedInt is 32 bits  -->
							<!--  unsignedShort is 16 bits  -->
							<xs:element name="ChnlName" type="xs:string"/>
							<xs:element name="Unit" type="xs:string" default="V"/>
							<xs:element name="ChnlId" type="xs:unsignedInt"/>
							<xs:element name="Len" type="xs:unsignedInt"/>
							<!--  Post = length after the trigger  -->
							<xs:element name="Post" type="xs:unsignedInt"/>
							<!--  MaxDat = maximum value for digitalization of the signal  -->
							<xs:element name="MaxDat" type="xs:unsignedInt" default="32768"/>
							<xs:element name="Freq" type="xs:decimal" default="1000"/>
							<xs:element name="LowRang" type="xs:decimal" default="0"/>
							<xs:element name="HighRang" type="xs:decimal" default="10"/>
							<xs:element name="Factor" type="xs:decimal" default="1"/>
							<xs:element name="Offset" type="xs:decimal" default="0"/>
							<xs:element name="Dly" type="xs:decimal" default="0"/>
							<xs:element name="DatAttr" type="xs:unsignedShort" default="1"/>
							<xs:element name="DatWth" type="xs:unsignedShort" default="2"/>
							<!--  additional information for channel  -->
							<xs:element name="division" type="xs:string"/>
							<xs:element name="personInCharge" type="xs:string"/>
							<xs:element name="fromPosition" type="xs:string"/>
							<xs:element name="insituPosition" type="xs:string"/>
							<xs:element name="implementationHistory" type="xs:string" default="2019.04.04"/>
							<xs:element name="channelDescription" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hunter-asd/XSW/acq/templates/acq/ModelACQ.XML
<?xml version="1.0" encoding="utf-8"?><!-- for EXL machine --><?xml-stylesheet type="text/xsl" href="ACQ.xsl"?><!--  EXL ACQ configuration file
-->
<ACQ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ACQ.xsd">
<Header>
<version>1.0</version>
<operator>songx</operator>
<shotnum>04896</shotnum>
</Header>
<Channel>
<ChnlName>AXUV</ChnlName>
<Unit>V</Unit>
<ChnlId>1</ChnlId>
<Len>500000</Len>
<Post>500000</Post>
<MaxDat>32768</MaxDat>
<Freq>50000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ1</channelDescription>
</Channel>
<Channel>
<ChnlName>SXR</ChnlName>
<Unit>V</Unit>
<ChnlId>2</ChnlId>
<Len>750000</Len>
<Post>500000</Post>
<MaxDat>32768</MaxDat>
<Freq>50000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ1</channelDescription>
</Channel>
<Channel>
<ChnlName>HXR</ChnlName>
<Unit>V</Unit>
<ChnlId>3</ChnlId>
<Len>750000</Len>
<Post>500000</Post>
<MaxDat>32768</MaxDat>
<Freq>50000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ1</channelDescription>
</Channel>
<Channel>
<ChnlName>VF</ChnlName>
<Unit>V</Unit>
<ChnlId>4</ChnlId>
<Len>1000000</Len>
<Post>1000000</Post>
<MaxDat>32768</MaxDat>
<Freq>200000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ1</channelDescription>
</Channel>
<Channel>
<ChnlName>EP</ChnlName>
<Unit>V</Unit>
<ChnlId>5</ChnlId>
<Len>2500000</Len>
<Post>2500000</Post>
<MaxDat>32768</MaxDat>
<Freq>500000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ1</channelDescription>
</Channel>
<Channel>
<ChnlName>MIR</ChnlName>
<Unit>V</Unit>
<ChnlId>6</ChnlId>
<Len>2500000</Len>
<Post>2500000</Post>
<MaxDat>32768</MaxDat>
<Freq>500000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ1</channelDescription>
</Channel>
<Channel>
<ChnlName>G1_ECRH</ChnlName>
<Unit>V</Unit>
<ChnlId>7</ChnlId>
<Len>1500000</Len>
<Post>1000000</Post>
<MaxDat>32768</MaxDat>
<Freq>100000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ2</channelDescription>
</Channel>
<Channel>
<ChnlName>G1_RF</ChnlName>
<Unit>V</Unit>
<ChnlId>8</ChnlId>
<Len>1500000</Len>
<Post>1000000</Post>
<MaxDat>32768</MaxDat>
<Freq>100000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ2</channelDescription>
</Channel>
<Channel>
<ChnlName>HA</ChnlName>
<Unit>V</Unit>
<ChnlId>9</ChnlId>
<Len>3000000</Len>
<Post>2000000</Post>
<MaxDat>32768</MaxDat>
<Freq>200000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ1</channelDescription>
</Channel>
<Channel>
<ChnlName>G1_VEC</ChnlName>
<Unit>V</Unit>
<ChnlId>10</ChnlId>
<Len>12000</Len>
<Post>12000</Post>
<MaxDat>32768</MaxDat>
<Freq>100</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ2</channelDescription>
</Channel>
<Channel>
<ChnlName>G1_ECRH_F</ChnlName>
<Unit>V</Unit>
<ChnlId>11</ChnlId>
<Len>6000000</Len>
<Post>5000000</Post>
<MaxDat>32768</MaxDat>
<Freq>1000000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ2</channelDescription>
</Channel>
<Channel>
<ChnlName>M1_ECRH</ChnlName>
<Unit>V</Unit>
<ChnlId>12</ChnlId>
<Len>1500000</Len>
<Post>1000000</Post>
<MaxDat>32768</MaxDat>
<Freq>100000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ2</channelDescription>
</Channel>
<Channel>
<ChnlName>GAS</ChnlName>
<Unit>V</Unit>
<ChnlId>13</ChnlId>
<Len>1500000</Len>
<Post>1000000</Post>
<MaxDat>32768</MaxDat>
<Freq>100000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ2</channelDescription>
</Channel>
<Channel>
<ChnlName>G1_TEC</ChnlName>
<Unit>V</Unit>
<ChnlId>14</ChnlId>
<Len>12000</Len>
<Post>12000</Post>
<MaxDat>32768</MaxDat>
<Freq>100</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ2</channelDescription>
</Channel>
<Channel>
<ChnlName>MWI</ChnlName>
<Unit>V</Unit>
<ChnlId>15</ChnlId>
<Len>1000000</Len>
<Post>600000</Post>
<MaxDat>32768</MaxDat>
<Freq>100000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ4</channelDescription>
</Channel>
<Channel>
<ChnlName>MPT</ChnlName>
<Unit>V</Unit>
<ChnlId>16</ChnlId>
<Len>2500000</Len>
<Post>1500000</Post>
<MaxDat>32768</MaxDat>
<Freq>100000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ3</channelDescription>
</Channel>
<Channel>
<ChnlName>MPN</ChnlName>
<Unit>V</Unit>
<ChnlId>17</ChnlId>
<Len>2500000</Len>
<Post>1500000</Post>
<MaxDat>32768</MaxDat>
<Freq>100000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
<fromPosition>Mr Guo dong</fromPosition>
<insituPosition>0</insituPosition>
<implementationHistory>2019</implementationHistory>
<channelDescription>ACQ3</channelDescription>
</Channel>
<Channel>
<ChnlName>FLUX</ChnlName>
<Unit>V</Unit>
<ChnlId>18</ChnlId>
<Len>2500000</Len>
<Post>1500000</Post>
<MaxDat>32768</MaxDat>
<Freq>100000</Freq>
<LowRang>0</LowRang>
<HighRang>10</HighRang>
<Factor>1</Factor>
<Offset>0</Offset>
<Dly>0</Dly>
<DatAttr>1</DatAttr>
<DatWth>2</DatWth>
<division>control group</division>
<personInCharge>yang</personInCharge>
