=== hunter-asd/XSW/dpf/templates/dpf/DPF.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- EXL machine control information -->
<!-- Discharge Programme File -->
<!--  designed by Dr Song xianming  -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="opMode">
		<xs:restriction base="xs:integer">
			<xs:enumeration value="0"/>
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
			<xs:enumeration value="3"/>
			<xs:enumeration value="4"/>
			<xs:enumeration value="5"/>
			<xs:enumeration value="6"/>
			<xs:enumeration value="12"/>
			<xs:enumeration value="56"/>
			<xs:enumeration value="-12"/>
			<xs:enumeration value="-34"/>
			<xs:enumeration value="-56"/>
			<xs:enumeration value="-1"/>
			<xs:enumeration value="-2"/>
			<xs:enumeration value="-3"/>
			<xs:enumeration value="-4"/>
			<xs:enumeration value="-5"/>
			<xs:enumeration value="-6"/>
			<!-- for example, null=0,only positive=1 only negative=2,both pos and neg=3, multi zerocross=4-->
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="zeroOne">
		<xs:restriction base="xs:integer">
			<xs:enumeration value="0"/>
			<xs:enumeration value="1"/>
			<!-- not take part in=0, should take part in=1 -->
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="DPF">
		<xs:annotation>
			<xs:documentation>Units in this file: current=kA, voltage=V, length=mm, time=ms</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Header">
					<xs:annotation>
						<xs:documentation>header information</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="version" type="xs:decimal" default="1.0"/>
							<xs:element name="operator" type="xs:string" default="songxm"/>
							<xs:element name="shotnum" type="xs:string" default="20000"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="OperationMode" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>operational mode, enumeration type, first use integer for code simplicity</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="value">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="-56"/>
										<xs:maxInclusive value="56"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="comment" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Command" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Command for subsystem to run, name is the subsys name, value mean in(1) or out(0)</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="value" type="zeroOne"/>
							<xs:element name="personInCharge" type="xs:string"/>
							<xs:element name="implementationHistory" type="xs:string"/>
							<xs:element name="db" type="zeroOne"/>
							<xs:element name="comment" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="PIDcontroller" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>PID parameter for all controller</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="P" type="xs:decimal"/>
							<xs:element name="I" type="xs:decimal"/>
							<xs:element name="D" type="xs:decimal"/>
							<xs:element name="RC" type="xs:decimal"/>
							<xs:element name="maxdU" type="xs:decimal"/>
							<xs:element name="FBStart" type="xs:decimal"/>
							<xs:element name="maxInvAngle" type="xs:decimal"/>
							<xs:element name="personInCharge" type="xs:string"/>
							<xs:element name="implementationHistory" type="xs:string"/>
							<xs:element name="comment" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="EngineeringLimit" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>PID parameter for all controller</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="value" type="xs:decimal"/>
							<xs:element name="personInCharge" type="xs:string"/>
							<xs:element name="implementationHistory" type="xs:string"/>
							<xs:element name="comment" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Other" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>other parameters,need a name and value</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="value" type="xs:decimal"/>
							<xs:element name="remark" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hunter-asd/XSW/dpf/templates/DPF/ModelDPF.XML
<DPF xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DPF.xsd">
<Header>
<version>1.0</version>
<operator>liuyong</operator>
<shotnum>05098</shotnum>
</Header>
<OperationMode>
<name>RZMode</name>
<value>0</value>

</OperationMode>
<OperationMode>
<name>PowerSource</name>
<value>0</value>

</OperationMode>
<OperationMode>
<name>FB</name>
<value>1</value>

</OperationMode>
<Command>
<name>GENERATOR</name>
<value>1</value>
<personInCharge>luowenwu</personInCharge>
<implementationHistory>2020.01.02</implementationHistory>
<db>0</db>
<comment>no</comment>
</Command>
<Command>
<name>EXCITATION</name>
<value>1</value>
<personInCharge>luowenwu</personInCharge>
<implementationHistory>2020.01.02</implementationHistory>
<db>0</db>
<comment>no</comment>
</Command>
<Command>
<name>TF</name>
<value>1</value>
<personInCharge>guanyupeng</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>no</comment>
</Command>
<Command>
<name>FBC</name>
<value>1</value>
<personInCharge>liuyong</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>no</comment>
</Command>
<Command>
<name>ECRH400A</name>
<value>0</value>
<personInCharge>zhouqing</personInCharge>
<implementationHistory>2020.4.24</implementationHistory>
<db>0</db>
<comment>ECRH400A</comment>
</Command>
<Command>
<name>ECRH400B</name>
<value>0</value>
<personInCharge>zhouqing</personInCharge>
<implementationHistory>2020.4.24</implementationHistory>
<db>0</db>
<comment>ECRH400B</comment>
</Command>
<Command>
<name>ECRH28</name>
<value>0</value>
<personInCharge>zhouqing</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>ECRH28</comment>
</Command>
<Command>
<name>ECRH245A</name>
<value>0</value>
<personInCharge>zhouqing</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>ECRH245A </comment>
</Command>
<Command>
<name>ECRH245B</name>
<value>1</value>
<personInCharge>zhouqing</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>ECRH245B</comment>
</Command>
<Command>
<name>ECRH245C</name>
<value>1</value>
<personInCharge>zhouqing</personInCharge>
<implementationHistory>2019.12.2</implementationHistory>
<db>0</db>
<comment>ECRH245C</comment>
</Command>
<Command>
<name>PS1</name>
<value>1</value>
<personInCharge>guanyupeng</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>PS1_PF56</comment>
</Command>
<Command>
<name>PS2</name>
<value>1</value>
<personInCharge>guanyupeng</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>PS2_PF4</comment>
</Command>
<Command>
<name>PS3</name>
<value>1</value>
<personInCharge>guanyupeng</personInCharge>
<implementationHistory>2020.01.17</implementationHistory>
<db>0</db>
<comment>PS3_PF1-2</comment>
</Command>
<Command>
<name>VAC</name>
<value>1</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>Vacuum Vessel</comment>
</Command>
<Command>
<name>GP</name>
<value>1</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>gas puff</comment>
</Command>
<Command>
<name>ACQ1</name>
<value>1</value>
<personInCharge>lunxiuchun</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>data acquisition 1</comment>
</Command>
<Command>
<name>ACQ2</name>
<value>1</value>
<personInCharge>lunxiuhcun</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>data acquisition 2</comment>
</Command>
<Command>
<name>ACQ3</name>
<value>1</value>
<personInCharge>lunxiuchun</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>data acquisition 3</comment>
</Command>
<Command>
<name>ACQ4</name>
<value>1</value>
<personInCharge>lunxiuchun</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>data acquisition 4</comment>
</Command>
<Command>
<name>MAC</name>
<value>1</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>Machine</comment>
</Command>
<Command>
<name>TCN</name>
<value>1</value>
<personInCharge>liuyong</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>TCN</comment>
</Command>
<Command>
<name>Water</name>
<value>0</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<db>0</db>
<comment>Water</comment>
</Command>
<PIDcontroller>
<name>TF</name>
<P>0</P>
<I>1</I>
<D>1</D>
<RC>10</RC>
<maxdU>20</maxdU>
<FBStart>12000</FBStart>
<maxInvAngle>-2</maxInvAngle>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</PIDcontroller>
<PIDcontroller>
<name>PS1</name>
<P>0.1</P>
<I>40</I>
<D>1</D>
<RC>10</RC>
<maxdU>20</maxdU>
<FBStart>-2000</FBStart>
<maxInvAngle>-2</maxInvAngle>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>PF56</comment>
</PIDcontroller>
<PIDcontroller>
<name>PS2</name>
<P>0.1</P>
<I>15</I>
<D>1</D>
<RC>10</RC>
<maxdU>20</maxdU>
<FBStart>-2000</FBStart>
<maxInvAngle>-2</maxInvAngle>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>PF4</comment>
</PIDcontroller>
<PIDcontroller>
<name>PS3</name>
<P>0.01</P>
<I>50</I>
<D>5</D>
<RC>10</RC>
<maxdU>5</maxdU>
<FBStart>-2000</FBStart>
<maxInvAngle>-2</maxInvAngle>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>PF1-2</comment>
</PIDcontroller>
<PIDcontroller>
<name>PS4</name>
<P>10</P>
<I>10</I>
<D>10</D>
<RC>10</RC>
<maxdU>20</maxdU>
<FBStart>-1000</FBStart>
<maxInvAngle>-2</maxInvAngle>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</PIDcontroller>
<PIDcontroller>
<name>PS5</name>
<P>10</P>
<I>10</I>
<D>10</D>
<RC>10</RC>
<maxdU>20</maxdU>
<FBStart>-1000</FBStart>
<maxInvAngle>-2</maxInvAngle>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</PIDcontroller>
<PIDcontroller>
<name>PS6</name>
<P>10</P>
<I>10</I>
<D>10</D>
<RC>10</RC>
<maxdU>20</maxdU>
<FBStart>-1000</FBStart>
<maxInvAngle>-2</maxInvAngle>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</PIDcontroller>
<PIDcontroller>
<name>ECRH</name>
<P>10</P>
<I>10</I>
<D>10</D>
<RC>10</RC>
<maxdU>20</maxdU>
<FBStart>-1000</FBStart>
<maxInvAngle>0</maxInvAngle>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</PIDcontroller>
<PIDcontroller>
<name>NE</name>
<P>10</P>
<I>10</I>
<D>10</D>
<RC>10</RC>
<maxdU>20</maxdU>
<FBStart>200</FBStart>
<maxInvAngle>0</maxInvAngle>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</PIDcontroller>
<PIDcontroller>
<name>W1</name>
<P>10</P>
<I>10</I>
<D>10</D>
<RC>10</RC>
<maxdU>20</maxdU>
<FBStart>-1000</FBStart>
<maxInvAngle>-2</maxInvAngle>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</PIDcontroller>
<PIDcontroller>
<name>PH</name>
<P>1</P>
<I>50</I>
<D>1</D>
<RC>10</RC>
<maxdU>5</maxdU>
<FBStart>-1000</FBStart>
<maxInvAngle>0</maxInvAngle>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</PIDcontroller>
<PIDcontroller>
<name>PV</name>
<P>1</P>
<I>50</I>
<D>1</D>
<RC>10</RC>
<maxdU>5</maxdU>
<FBStart>-1000</FBStart>
<maxInvAngle>0</maxInvAngle>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</PIDcontroller>
<EngineeringLimit>
<name>ITF</name>
<value>25</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</EngineeringLimit>
<EngineeringLimit>
<name>Ip</name>
<value>100</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</EngineeringLimit>
<EngineeringLimit>
<name>IPF1</name>
<value>2000</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</EngineeringLimit>
<EngineeringLimit>
<name>IPF2</name>
<value>2000</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</EngineeringLimit>
<EngineeringLimit>
<name>IPF3</name>
<value>4500</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</EngineeringLimit>
<EngineeringLimit>
<name>IPF4</name>
<value>20</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</EngineeringLimit>
<EngineeringLimit>
<name>IPF5</name>
<value>10</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</EngineeringLimit>
<EngineeringLimit>
<name>IPF6</name>
<value>10</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2019.3.15</implementationHistory>
<comment>no</comment>
</EngineeringLimit>
<EngineeringLimit>
<name>NELimit</name>
<value>0.01</value>
<personInCharge>Dr. Liu</personInCharge>
<implementationHistory>2020.3.16</implementationHistory>
<comment>ne min error of pid</comment>
</EngineeringLimit>
<EngineeringLimit>
<name>dWLimit</name>
<value>1</value>
