=== hunter-asd/XSW/tcn/templates/tcn/timingOutputSignals.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="timingOutputSignal">
		<xs:complexType>
			<xs:sequence>
			
				<xs:element name="Header">
					<xs:annotation>
						<xs:documentation>header information</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="version" type="xs:decimal" default="1.0"/>
							<xs:element name="operator" type="xs:string" default="songxm"/>
							<xs:element name="shotnum" type="xs:string" default="20000"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="outputSignal" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>The root element is usually named the same as the doctype.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="id" type="xs:string"/>
							<xs:element name="initialValue" type="xs:boolean" default="false"/>
							<xs:element name="timeUnit" type="xs:string" default="ms"/>
							<xs:element name="attachedInformation">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="division" type="xs:string"/>
										<xs:element name="personInCharge" type="xs:string"/>
										<xs:element name="toPosition" type="xs:string"/>
										<xs:element name="insituPosition" type="xs:string"/>
										<xs:element name="implementationHistory" type="xs:string"/>
										<xs:element name="comment" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="triggerConditions" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="isSigmaInverse" type="xs:boolean" default="false"/>
										<xs:element name="orSignals" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="andSignals" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="isInverse" type="xs:boolean" default="false"/>
																<xs:element name="andSignalName" type="xs:string"/>
																<xs:element name="delayTime" type="xs:decimal" default="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="pulseClass" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="repeatNumber" type="xs:decimal" default="1"/>
										<xs:element name="timingMode">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="absolute"/>
													<xs:enumeration value="referenceToLastPulse"/>
													<xs:enumeration value="referenceToConditions"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="startTime" type="xs:decimal" default="0"/>
										<xs:element name="lowWidth" type="xs:decimal" default="0"/>
										<xs:element name="highWidth" type="xs:decimal" default="1000"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hunter-asd/XSW/tcn/templates/tcn/04653OUT.XML
<?xml version="1.0" encoding="utf-8"?><?xml-stylesheet type="text/xsl" href="timingOutputSignals.xsl"?>
<timingOutputSignal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../timingOutputSignals.xsd">
<Header>
<version>11.0</version>
<operator>songxm</operator>
<shotnum>04653</shotnum>
</Header>
	<!--CCLaunch -->
<outputSignal>
<name>CCLaunch</name>
<id>1001</id><!--1000+端口号-->
<initialValue>true</initialValue>
<timeUnit>ms</timeUnit>
<attachedInformation>
<division>ctrlGroup</division>
<personInCharge>YanEnwu</personInCharge>
<toPosition>PLC cabinet</toPosition>
<insituPosition>2</insituPosition>
<implementationHistory>20190617</implementationHistory>
<comment>ECRH28</comment>
</attachedInformation>
<triggerConditions>
<isSigmaInverse>true</isSigmaInverse>
<orSignals>
<andSignals>
<isInverse>false</isInverse>
<andSignalName>Sigma0</andSignalName>
<ContinuousSigma1Check>0</ContinuousSigma1Check>
<isProtection>0</isProtection>
<delayTime>0</delayTime>
</andSignals>
</orSignals>
</triggerConditions>
<pulseClass>
<repeatNumber>1</repeatNumber>
<timingMode>absolute</timingMode>
<startTime>-60000</startTime>
<lowWidth>0</lowWidth>
<highWidth>80000</highWidth><!--脉冲宽度-->
</pulseClass>
</outputSignal>
	<!--EMIntergratorStart-->
<outputSignal>
<name>ECRH28</name>
<id>1020</id>
<initialValue>true</initialValue>
<timeUnit>ms</timeUnit>
<attachedInformation>
<division>AuxiliaryHeating</division>
<personInCharge>SongShaodong</personInCharge>
<toPosition>HeatCabinet</toPosition>
<insituPosition>20</insituPosition>
<implementationHistory>20190902</implementationHistory>
<comment>trigger for28GHz</comment>
</attachedInformation>
<triggerConditions>
<isSigmaInverse>true</isSigmaInverse>
<orSignals>
<andSignals>
<isInverse>false</isInverse>
<andSignalName>Sigma0</andSignalName>
<ContinuousSigma1Check>0</ContinuousSigma1Check>
<isProtection>0</isProtection>
<delayTime>0</delayTime>
</andSignals>
</orSignals>
</triggerConditions>
<pulseClass>
<repeatNumber>1</repeatNumber>
<timingMode>absolute</timingMode>
<startTime>0</startTime>
<lowWidth>0</lowWidth>
<highWidth>3500</highWidth>
</pulseClass>
</outputSignal>
<outputSignal>
<name>ECRH245C</name>
<id>1019</id>
<initialValue>true</initialValue>
<timeUnit>ms</timeUnit>
<attachedInformation>
<division>AuxiliaryHeating</division>
<personInCharge>SongShaodong</personInCharge>
<toPosition>HeatCabinet</toPosition>
<insituPosition>19</insituPosition>
<implementationHistory>20191202</implementationHistory>
<comment>pre trigger for 2.45GHz</comment>
</attachedInformation>
<triggerConditions>
<isSigmaInverse>true</isSigmaInverse>
<orSignals>
<andSignals>
<isInverse>false</isInverse>
<andSignalName>Sigma0</andSignalName>
<ContinuousSigma1Check>0</ContinuousSigma1Check>
<isProtection>0</isProtection>
<delayTime>0</delayTime>
</andSignals>
</orSignals>
</triggerConditions>
<pulseClass>
<repeatNumber>1</repeatNumber>
<timingMode>absolute</timingMode>
<startTime>-1500</startTime>
<lowWidth>0</lowWidth>
<highWidth>2000</highWidth>
</pulseClass>
</outputSignal>
	<!--ECRHStart-->
<outputSignal>
<name>Pre_ECRH28</name>
<id>1021</id>
<initialValue>true</initialValue>
<timeUnit>ms</timeUnit>
<attachedInformation>
<division>diagnostic</division>
<personInCharge>shaodong</personInCharge>
<toPosition>diagnostic</toPosition>
<insituPosition>21</insituPosition>
<implementationHistory>20191227</implementationHistory>
<comment>ECRH28</comment>
</attachedInformation>
<triggerConditions>
<isSigmaInverse>true</isSigmaInverse>
<orSignals>
<andSignals>
<isInverse>false</isInverse>
<andSignalName>Sigma0</andSignalName>
<ContinuousSigma1Check>0</ContinuousSigma1Check>
<isProtection>0</isProtection>
<delayTime>0</delayTime>
</andSignals>
</orSignals>
</triggerConditions>
<pulseClass>
<repeatNumber>1</repeatNumber>
<timingMode>absolute</timingMode>
<startTime>-2000</startTime>
<lowWidth>0</lowWidth>
<highWidth>7000</highWidth>
</pulseClass>
</outputSignal>
	<!--ECRHStart-->
<outputSignal>
<name>Excitation</name>
<id>1013</id>
<initialValue>true</initialValue>
<timeUnit>ms</timeUnit>
<attachedInformation>
<division>VacuumVesse</division>
<personInCharge>ZhaoXin</personInCharge>
<toPosition>VacuumVessel</toPosition>
<insituPosition>13</insituPosition>
<implementationHistory>20191112</implementationHistory>
<comment>no</comment>
</attachedInformation>
<triggerConditions>
<isSigmaInverse>true</isSigmaInverse>
<orSignals>
<andSignals>
<isInverse>false</isInverse>
<andSignalName>Sigma0</andSignalName>
<ContinuousSigma1Check>0</ContinuousSigma1Check>
<isProtection>0</isProtection>
<delayTime>0</delayTime>
</andSignals>
</orSignals>
</triggerConditions>
<pulseClass>
<repeatNumber>1</repeatNumber>
<timingMode>absolute</timingMode>
<startTime>-7000</startTime>
<lowWidth>0</lowWidth>
<highWidth>12000</highWidth>
</pulseClass>
</outputSignal>
	<!--ECRH2-->
<outputSignal>
<name>ECRH245A</name>
<id>1029</id>
<initialValue>true</initialValue>
<timeUnit>ms</timeUnit>
<attachedInformation>
<division>AuxiliaryHeating</division>
<personInCharge>SongShaodong</personInCharge>
<toPosition>HeatCabinet</toPosition>
<insituPosition>29</insituPosition>
<implementationHistory>20190617</implementationHistory>
<comment>pre trigger for 2.45GHz/connected</comment>
</attachedInformation>
<triggerConditions>
<isSigmaInverse>true</isSigmaInverse>
<orSignals>
<andSignals>
<isInverse>false</isInverse>
<andSignalName>Sigma0</andSignalName>
<ContinuousSigma1Check>0</ContinuousSigma1Check>
<isProtection>0</isProtection>
<delayTime>0</delayTime>
</andSignals>
</orSignals>
</triggerConditions>
<pulseClass>
<repeatNumber>1</repeatNumber>
<timingMode>absolute</timingMode>
<startTime>-1200</startTime>
<lowWidth>0</lowWidth>
<highWidth>3700</highWidth>
</pulseClass>
</outputSignal>
	<!--TF-->
<outputSignal>
<name>PRE_ECRH245A_C</name>
<id>1028</id>
<initialValue>true</initialValue>
<timeUnit>ms</timeUnit>
<attachedInformation>
<division>AuxiliaryHeating</division>
<personInCharge>SongShaodong</personInCharge>
<toPosition>HeatCabinet</toPosition>
<insituPosition>28</insituPosition>
<implementationHistory>20190617</implementationHistory>
<comment>pre trigger for 2.45GHz/connected</comment>
</attachedInformation>
<triggerConditions>
<isSigmaInverse>true</isSigmaInverse>
<orSignals>
<andSignals>
<isInverse>false</isInverse>
<andSignalName>Sigma0</andSignalName>
<ContinuousSigma1Check>0</ContinuousSigma1Check>
<isProtection>0</isProtection>
<delayTime>0</delayTime>
</andSignals>
</orSignals>
</triggerConditions>
<pulseClass>
<repeatNumber>1</repeatNumber>
<timingMode>absolute</timingMode>
<startTime>-55000</startTime>
<lowWidth>0</lowWidth>
<highWidth>59500</highWidth>
</pulseClass>
</outputSignal>
	<!--PS1-->
<outputSignal>
<name>GP1</name>
<id>1025</id>
<initialValue>true</initialValue>
<timeUnit>ms</timeUnit>
<attachedInformation>
<division>VacuumVessel</division>
<personInCharge>ZhaoXin</personInCharge>
<toPosition>VacuumVessel</toPosition>
<insituPosition>525</insituPosition>
<implementationHistory>20190617</implementationHistory>
<comment>no</comment>
</attachedInformation>
<triggerConditions>
<isSigmaInverse>true</isSigmaInverse>
<orSignals>
<andSignals>
<isInverse>false</isInverse>
<andSignalName>Sigma0</andSignalName>
<ContinuousSigma1Check>0</ContinuousSigma1Check>
<isProtection>0</isProtection>
<delayTime>0</delayTime>
</andSignals>
</orSignals>
</triggerConditions>
<pulseClass>
<repeatNumber>1</repeatNumber>
<timingMode>absolute</timingMode>
<startTime>0</startTime>
<lowWidth>0</lowWidth>
<highWidth>0</highWidth>
</pulseClass>
</outputSignal>
	<!--PS2-->
<outputSignal>
<name>GP2</name>
<id>1026</id>
<initialValue>true</initialValue>
<timeUnit>ms</timeUnit>
<attachedInformation>
<division>VacuumVesse</division>
<personInCharge>ZhaoXin</personInCharge>
<toPosition>VacuumVessel</toPosition>
<insituPosition>526</insituPosition>
<implementationHistory>20190617</implementationHistory>
<comment>no</comment>
</attachedInformation>
<triggerConditions>
<isSigmaInverse>true</isSigmaInverse>
<orSignals>
<andSignals>
<isInverse>false</isInverse>
<andSignalName>Sigma0</andSignalName>
<ContinuousSigma1Check>0</ContinuousSigma1Check>
<isProtection>0</isProtection>
<delayTime>0</delayTime>
</andSignals>
</orSignals>
</triggerConditions>
<pulseClass>
<repeatNumber>1</repeatNumber>
<timingMode>absolute</timingMode>
<startTime>0</startTime>
<lowWidth>0</lowWidth>
<highWidth>0</highWidth>
</pulseClass>
</outputSignal>
	<!--FBC-->
<outputSignal>
<name>ECRH245B</name>
<id>1027</id>
<initialValue>true</initialValue>
<timeUnit>ms</timeUnit>
<attachedInformation>
<division>AuxiliaryHeating</division>
<personInCharge>SongShaodong</personInCharge>
<toPosition>HeatCabinet</toPosition>
<insituPosition>27</insituPosition>
<implementationHistory>20190617</implementationHistory>
<comment>pre trigger for 2.45GHz</comment>
</attachedInformation>
<triggerConditions>
<isSigmaInverse>true</isSigmaInverse>
<orSignals>
<andSignals>
<isInverse>false</isInverse>
<andSignalName>Sigma0</andSignalName>
<ContinuousSigma1Check>0</ContinuousSigma1Check>
<isProtection>0</isProtection>
<delayTime>0</delayTime>
</andSignals>
</orSignals>
</triggerConditions>
<pulseClass>
<repeatNumber>1</repeatNumber>
<timingMode>absolute</timingMode>
<startTime>-1500</startTime>
<lowWidth>0</lowWidth>
<highWidth>5500</highWidth>
</pulseClass>
</outputSignal>
	<!--HSC-->
<outputSignal>
<name>NC5</name>
<id>1022</id>
<initialValue>true</initialValue>
<timeUnit>ms</timeUnit>
<attachedInformation>
<division>diagnostic</division>
<personInCharge>future</personInCharge>
<toPosition>diagnostic</toPosition>
<insituPosition>523</insituPosition>
<implementationHistory>20190617</implementationHistory>
<comment>pre trigger to for Thomson scattering</comment>
</attachedInformation>
<triggerConditions>
<isSigmaInverse>true</isSigmaInverse>
<orSignals>
<andSignals>
<isInverse>false</isInverse>
<andSignalName>Sigma0</andSignalName>
<ContinuousSigma1Check>0</ContinuousSigma1Check>
